# Generated by Django 5.1.6 on 2025-03-11 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline_app.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('node_type', models.CharField(choices=[('CUSTOM', 'CUSTOM'), ('GITHUB', 'GITHUB'), ('GITLAB', 'GITLAB')], default='CUSTOM', max_length=50)),
                ('script', models.FileField(blank=True, null=True, upload_to='')),
                ('params', models.JSONField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline_app.pipeline')),
            ],
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['user'], name='pipeline_ap_user_id_2c3e98_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentvariable',
            index=models.Index(fields=['pipeline'], name='pipeline_ap_pipelin_467afa_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['pipeline', 'order'], name='pipeline_ap_pipelin_ecb776_idx'),
        ),
    ]
