# Generated by Django 5.1.6 on 2025-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_app", "0003_stage_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="script",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
