# Generated by Django 5.1.6 on 2025-02-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_app", "0004_alter_stage_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
