# Generated by Django 5.1.6 on 2025-02-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_app", "0005_stage_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pipeline_app.pipeline",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["pipeline"], name="pipeline_ap_pipelin_467afa_idx"
                    )
                ],
            },
        ),
    ]
