# Generated by Django 5.1.6 on 2025-03-04 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline_app", "0006_environmentvariable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="stage_type",
        ),
    ]
