# Generated by Django 5.1.6 on 2025-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_app', '0008_alter_stage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='node_type',
            field=models.CharField(choices=[('CUSTOM', 'Custom')], default='CUSTOM', max_length=50),
        ),
    ]
