# Generated by Django 5.1.6 on 2025-03-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_app', '0012_alter_stage_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
