# Generated by Django 5.1.6 on 2025-03-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_app', '0002_alter_githubprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubprofile',
            name='installation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='githubprofile',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
